import os

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 4
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_COLOR = (100,100,100)

ASTEROID_SPAWN_RATE = 1.2  
ASTEROID_MIN_SPAWN_RATE = 0.2
ASTEROID_SPAWN_RATE_INCREASE_TIMER = 10
ASTEROID_SPAWN_RATE_CHANGE = .1


PLAYER_RADIUS = 20

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_ACCELERATION = 500
PLAYER_MAX_SPEED = 1500
PLAYER_DRAG = .7

PLAYER_SHOOT_COOLDOWN = 0.075
PLAYER_SHOOT_SPEED = 500
SHOT_RADIUS = 2

BG_SECONDARY = (0,0,82)
BG_SPEED = .8

# DO NOT EDIT BELOW THIS LINE!!!

HUD_WIDTH = 200
HUD_HEIGHT = 60
HUD_Y = 10
HUD_COLOR = 30, 30, 30
HUD_X = SCREEN_WIDTH - HUD_WIDTH - 10  # 10 px from right


DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")
HIGHSCORE_FILE = os.path.join(DATA_DIR, "highscores.json")